joint_ids_map: [3, 0, 9, 6, 4, 1, 10, 7, 5, 2, 11, 8]
step_dt: 0.02
stiffness: [25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0]
damping: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
default_joint_pos: [0.1, -0.1, 0.1, -0.1, 0.8, 0.8, 1.0, 1.0, -1.5, -1.5, -1.5, -1.5]
commands: {}
actions:
  JointPositionAction:
    clip:
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    joint_names: [.*]
    scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
    offset: [0.1, -0.1, 0.1, -0.1, 0.8, 0.8, 1.0, 1.0, -1.5, -1.5, -1.5, -1.5]
    joint_ids: null
observations:
  base_lin_vel:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0]
    history_length: 1
  base_ang_vel:
    params: {}
    clip: [-100, 100]
    scale: [0.2, 0.2, 0.2]
    history_length: 1
  projected_gravity:
    params: {}
    clip: [-100, 100]
    scale: [1.0, 1.0, 1.0]
    history_length: 1
  position_commands:
    params: {command_name: step_fr_to_block}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  fr_target_xy_rel:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  leg_position:
    params: {}
    clip: null
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  joint_pos_rel:
    params: {}
    clip: [-100, 100]
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  joint_vel_rel:
    params: {}
    clip: [-100, 100]
    scale: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    history_length: 1
  last_action:
    params: {}
    clip: [-100, 100]
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
  ft_stack:
    params:
      sensor_cfg:
        name: contact_forces
        joint_names: null
        joint_ids: !!python/object/apply:builtins.slice [null, null, null]
        fixed_tendon_names: null
        fixed_tendon_ids: !!python/object/apply:builtins.slice [null, null, null]
        body_names: [.*_foot]
        body_ids: [4, 8, 14, 18]
        object_collection_names: null
        object_collection_ids: !!python/object/apply:builtins.slice [null, null, null]
        preserve_order: false
      mass_kg: 15.0
      return_shape: bkl3
    clip: [-3.0, 3.0]
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 1
